name: SharedWeblatePush

# SPDX-FileCopyrightText: 2026 Sangoma US Inc.
# SPDX-License-Identifier: GPL-3.0-or-later

# This workflow should be executed upon push to a weblate/x branch.
# It makes a new PR and then lints the push.

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write
  statuses: write

env:
  # These values should match your version numbers and grow with you.
  WEBLATE_BRANCH: ${{ endsWith(github.ref,'/16.0') && 'weblate/16.0' ||
                      endsWith(github.ref,'/17.0') && 'weblate/17.0' ||
                      endsWith(github.ref,'/18.0') && 'weblate/18.0' ||
                      'weblate/0' }}
  # The release/x numbering is nearly the same as the weblate/x numbering.
  RELEASE_BRANCH: ${{ endsWith(github.ref,'/16.0') && 'release/16.0' ||
                      endsWith(github.ref,'/17.0') && 'release/17.0' ||
                      endsWith(github.ref,'/18.0') && 'release/18.0' ||
                      'release/0' }}
    
jobs:
  MakePR:
    name: Auto make PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    concurrency:
      group: check-shared-weblate-push-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout full
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Checkout weblate/x branch
        run: git checkout "${WEBLATE_BRANCH}"

      - name: Make Pull Request
        id: make-pr-step
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh pr create \
            --head="${WEBLATE_BRANCH}" \
            --base="${RELEASE_BRANCH}" \
            --title="Pulling ${WEBLATE_BRANCH} into ${RELEASE_BRANCH}" \
            --body="An automated PR that was generated by a push to a weblate branch. If it fails to merge automatically to the corresponding release branch, then check for failures carefully before manually merging, e.g., linting issues, changes outside i18n directory, etc." \
            2> make-pr-error.log

      # Handle race condition between external Weblate and SharedReleasePush.yml
      - name: Only run if PR not made
        if: steps.make-pr-step.outcome != 'success'
        run: |
          {
            echo 'RACE_CONDITION<<EOF'
            grep -c -m 1 \
              "^pull request create failed: GraphQL: No commits between ${RELEASE_BRANCH} and ${WEBLATE_BRANCH} (createPullRequest)$" \
              make-pr-error.log
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Determine if failure to make PR is acceptable
        if: steps.make-pr-step.outcome != 'success'
        run: |
          cat make-pr-error.log
          if [ "${RACE_CONDITION}" == "1" ]; then
            echo "Ooh race condition detected - no worries - we didn't need the PR anyhow!"
          else
            echo "Uh oh it looks serious. Why no PR ?"
            exit 1
          fi

  LintAfterMake:
    needs: [ MakePR ]
    if: ${{ needs.MakePR.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout weblate/x branch
        run: git checkout "${WEBLATE_BRANCH}"

      - name: Super-linter slim validation only
        uses: super-linter/super-linter/slim@v8.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
